accounts/urls.py
from django import urls
from django.urls import path
from .views import signin, signup, profile,signout, recovery

app_name = 'accounts'

urlpatterns = [
    path('signin/', signin, name='signin'),
    path('signup/', signup, name='signup'),
    path('signout/', signout, name='signout'),
    path('profile/', profile, name='profile'),
    path('recovery/', recovery, name='recovery'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import signin_email
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('product.urls')),
    path('signin/email/<uidb64>/<token>/', signin_email, name='signin_email'),
)


if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from .sitemaps import ProductSitemap
from .views import (
                index, is_sending,product_single,delete_product,
                categories,about,all_products,contact_us,
                search, cart,add_to_basket,product_special,
                update_basket,remove_basket,pay,address,
                is_sending,show_order,is_send,create,edit
)

sitemaps = {
    'movie':ProductSitemap,
}

app_name = 'product'

urlpatterns = [
    path('', index, name='index'),
    path('product/single/<str:slug>/',product_single,name='product_single'),
    path('product/special/',product_special,name='product_special'),
    path('about/',about,name='about'),
    path('all/products/',all_products,name="all_products"),
    path('category/<str:name>/',categories,name='category'),
    path('contact/',contact_us,name='contact'),
    path('search/',search,name='search'),
    path('cart',cart ,name='cart'),
    path('add_to_basket/<int:pk>/',add_to_basket ,name='add_to_basket'),
    path('delete_product/', delete_product, name='delete_product'),
    path('update_basket/', update_basket, name='update_basket'),
    path('remove_basket/', remove_basket, name='remove_basket'),
    path('pay/', pay, name='pay'),
    path('address/<int:pk>/', address, name='address'),
    path('is_sending/', is_sending, name='is_sending'),
    path('show_order/<int:pk>/', show_order, name='show_order'),
    path('is_send/<int:pk>/', is_send, name='is_send'),
    path('edit/<int:pk>/', edit, name='edit'),
    path('create/', create, name='create'),
    path('sitemap/', sitemap, {'sitemaps':sitemaps}, name="sitemap"),

]

templates/base.html
{% load static %}
{% load navbar_left %}

<!DOCTYPE>
<html>
<head>
<title>Flower Shop</title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<link rel="stylesheet" href="{% static 'lightbox.css' %}" type="text/css" media="screen" />
<script src="{% static 'js/prototype.js' %}" type="text/javascript"></script>
<script src="{% static 'js/scriptaculous.js?load=effects' %}" type="text/javascript"></script>
<script src="{% static 'js/lightbox.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/java.js' %}"></script>

</head>
<body>
<div id="wrap">
    {% include  'nav/header.html' %}

    {% block body %}
    {% include  'nav/msg.html' %}

    {% endblock %}

    {% navbar request %}
    <!--end of right content-->
    <div class="clear"></div>
  </div>
  {% include 'nav/footer.html' %}
  
  {% block js %}

  {% endblock %}
 </html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}

{%if LANGUAGE_CODE == 'en' %}

  <div class="center_content">
    <div class="left_content">
      <div class="title"><span class="title_icon"><img src="{%static 'images/bullet1.gif' %}" alt="" /></span>My cart</div>
      <div class="feat_prod_box_details">
        <table class="cart_table">
          <tr class="cart_title">
            <td>Item pic</td>
            <td>Product name</td>
            <td>Unit price</td>
            <td>Qty</td>
            <td>Total</td>
            <td>Delete</td>
          </tr>
          {% for pro in products %}
          <tr>
            <td><a href=""><img style="width: 50px; height: 50px;" src="{{pro.product.image.url}}" alt="" border="0" class="cart_thumb" /></a></td>
            <td>{{pro.product.name}}</td>
            <td>{{pro.product.price_end_doller}}doller</td>
            <td>
              <form action="{% url 'product:update_basket' %}" method="POST">
                {% csrf_token %}
                <input type="number" name="number" min="1" max="{{pro.product.count}}" value="{{pro.qty}}">
                <input  type="number" name="pk" hidden readonly value="{{pro.pk}}">
                <input type="submit" style="height: 22px;width: 40px;" class="register" value="آپدیت">
              </form>
            </td>
            <td>{{pro.total_doller}}doller</td>
            <td style="height: 20px;width: 20px;">
              <form action="{% url 'product:delete_product' %}" method="POST">
                {% csrf_token %}
                <input  type="number" name="pk" hidden readonly value="{{pro.pk}}">
                <input type="submit" class="register" style="height: 22px;width: 40px;"value="حذف">
              </form>
            </td>
          </tr>
          {% endfor %}
          <tr>
            <td colspan="4" class="cart_total"><span class="red">TOTAL SHIPPING:</span></td>
            <td> {{total_doller}}$</td>
          </tr>
          
        </table>
        {% if basket %}
          <a href="{% url 'product:remove_basket' %}" class="continue"> delete_basket</a> <a href="{% url 'product:address' basket_pk %}" class="checkout">pay basket </a>
        {% endif %}  
        </div>
      <div class="clear"></div>
      <hr>
      <div class="title"><span class="title_icon"><img src="{% static 'images/bullet1.gif' %}" alt="" /></span>لیست سفارشات من</div>

      {% for tb in  basket_old%}  
      <div class="feat_prod_box_details">
        <table class="cart_table">
          <tr class="cart_title">
            <td>image</td>
            <td>product name</td>
            <td>price unit</td>
            <td>Qty</td>
            <td>price total</td>
          </tr>
          {% for pro in tb.basketproduct_user.all %}
          <tr>
            <td><a href=""><img style="width: 50px; height: 50px;" src="{{pro.product.image.url}}" alt="" border="0" class="cart_thumb" /></a></td>
            <td>{{pro.product.name}}</td>
            <td>{{pro.price_unit_doller}}$</td>
            <td>{{pro.qty}}</td>
            <td>{{pro.total_doller_paid}}$</td>
          </tr>
          {% endfor %}
          <tr>
            <td colspan="4" class="cart_total"><span class="red">مبلغ پرداخت شده:</span></td>
            <td>{{tb.money_paid}}</td>
          </tr>
          <tr>
            {% for addr in tb.basket_address.all %}

            <td colspan="1" class="cart_total"><span class="red">{{addr.number}}</span></td>
            <td colspan="4">{{ addr.address}}</td>
            {% endfor %}

          </tr>
        </table>
      </div>
      <div class="clear"></div>
        {% endfor %}
    </div>
{% endif %}
{%if LANGUAGE_CODE == 'fa' %}
 <div class="center_content">
    <div class="left_content">
      <div class="title"><span class="title_icon"><img src="{%static 'images/bullet1.gif' %}" alt="" /></span>My cart</div>
      <div class="feat_prod_box_details">
        <table class="cart_table">
          <tr class="cart_title">
            <td>Item pic</td>
            <td>Product name</td>
            <td>Unit price</td>
            <td>Qty</td>
            <td>Total</td>
            <td>Delete</td>
          </tr>
          {% for pro in products %}
          <tr>
            <td><a href=""><img style="width: 50px; height: 50px;" src="{{pro.product.image.url}}" alt="" border="0" class="cart_thumb" /></a></td>
            <td>{{pro.product.name}}</td>
            <td>{{pro.unit_price_rial}}ریال</td>
            <td>
              <form action="{% url 'product:update_basket' %}" method="POST">
                {% csrf_token %}
                <input type="number" name="number" min="1" max="10" value="{{pro.qty}}">
                <input  type="number" name="pk" hidden readonly value="{{pro.pk}}">
                <input type="submit" style="height: 22px;width: 40px;" class="register" value="آپدیت">
              </form>
            </td>
            <td>{{pro.total_rial}}doller</td>
            <td style="height: 20px;width: 20px;">
              <form action="{% url 'product:delete_product' %}" method="POST">
                {% csrf_token %}
                <input  type="number" name="pk" hidden readonly value="{{pro.pk}}">
                <input type="submit" class="register" style="height: 22px;width: 40px;"value="حذف">
              </form>
            </td>
          </tr>
          {% endfor %}
          <tr>
            <td colspan="4" class="cart_total"><span class="red">TOTAL SHIPPING:</span></td>
            <td> {{total_rial}}$</td>
          </tr>
          
        </table>
        {% if basket %}
          <a href="{% url 'product:remove_basket' %}" class="continue"> delete_basket</a> <a href="{% url 'product:address' %}" class="checkout">pay basket </a> 
        {% endif %}
        </div>
      <div class="clear"></div>
      <hr>
      <div class="title"><span class="title_icon"><img src="{% static 'images/bullet1.gif' %}" alt="" /></span>لیست سفارشات من</div>

      {% for tb in  basket_old%}  
      <div class="feat_prod_box_details">
        <table class="cart_table">
          <tr class="cart_title">
            <td>تصویر</td>
            <td>نام محصول</td>
            <td>قیمت واحد</td>
            <td>تعداد</td>
            <td>قیمت کل</td>
          </tr>
          {% for pro in tb.basketproduct_user.all %}
          <tr>
            <td><a href=""><img style="width: 50px; height: 50px;" src="{{pro.product.image.url}}" alt="" border="0" class="cart_thumb" /></a></td>
            <td>{{pro.product.name}}</td>
            <td>{{pro.price_unit_rial}}ریال</td>
            <td>{{pro.qty}}</td>
            <td>{{pro.total_rial}}ریال</td>
          </tr>
          {% endfor %}
          <tr>
            <td colspan="4" class="cart_total"><span class="red">مبلغ پرداخت شده:</span></td>
            <td>{{tb.money_paid}}</td>
          </tr>
          <tr>
            {% for addr in tb.basket_address.all %}

            <td colspan="1" class="cart_total"><span class="red">{{addr.number}}</span></td>
            <td colspan="4">{{ addr.address}}</td>
            {% endfor %}

          </tr>
        </table>
      </div>
      <div class="clear"></div>
        {% endfor %}
    </div>
{% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}

{%if LANGUAGE_CODE == 'en' %}
  <div class="center_content">
    <div class="left_content">
    <form action="{% url 'product:search' %}" method = 'GET'>
          <input type="number" name="price_down" {% if price_down %}value="{{price_down}}"{% endif %}placeholder="(100000)کمتر از"> 
          <input type="text" size="10" name="name"{% if name %}value="{{name}}"{% endif %} placeholder="نام محصول">
          <p>
            <input type="number" name="price_up" {% if price_up %}value="{{price_up}}"{% endif %} placeholder="(1000)بیشتر از"> 
            <select name="category">
              <option {% if category %}value="{{category}}"{% else %} value="" {% endif %}>{% if category %} {{category}} {% else %} --- {% endif %}</option>
              {% for cat in categories %}
                <option  value="{{cat.name_en}}">{{cat.name_en}}</option>
              {% endfor %} 
              </select>
            <input type="submit" class="register" value="سرچ"> 
          </p>
    </form>
      <div class="title"><span class="title_icon"><img src="images/bullet1.gif" alt="" /></span>all products</div>
      <div class="new_products">
       
      {% for pro in searchs %}
        <div class="new_prod_box"> <a href="{% url 'product:product_single' pro.slug %}">{{ pro.name_en }}</a>
          <div class="new_prod_bg"> <span class="new_icon">
          {% if pro.status == 'new' %}
            <img src="{% static 'images/new_icon.gif' %}" alt="" />
          {% endif %}
          {% if pro.status == 'promo' %}
            <img src="{% static 'images/promo_icon.gif' %}" alt="" />
          {% endif %}
          {% if pro.status == 'special' %}
            <img src="{% static 'images/special_icon.gif' %}" alt="" />
          {% endif %}
          </span> <a href="{% url 'product:product_single' pro.slug %}"><img src="{{ pro.image.url }}" alt="" class="thumb" border="0" /></a> </div>
        </div>
      {% endfor %}


      {% if searchs.has_other_pages %}
        <div class="pagination">
          {% if searchs.has_previous %}
          <a href="?page={{searchs.previous_page_number}}"><<</a>
          {% else %}
          <span class="disabled"><<</span>
          {% endif %}
          {% for i in product.paginator.page_range %} 
            {% if searchs.number == i %}
            <a>{{i}}</a>
            {% else %}
              <a href="?page={{i}}">{{i}}</a>
            {% endif %}
          {% endfor %}
          {% if searchs.has_next %}
            <a href="?page={{searchs.next_page_number}}">>></a>
          {% else %}
          <span class="disabled">>></span>
          {% endif %}
        </div>
      {% endif %}


    </div>
    <div class="clear"></div>
  </div>
{% endif %}
{%if LANGUAGE_CODE == 'fa' %}
<div class="center_content">
    <div class="left_content">
      <div class="title"><span class="title_icon"><img src="images/bullet1.gif" alt="" /></span>all products</div>
      <div class="new_products">
       
      {% for pro in products %}
        <div class="new_prod_box"> <a href="{% url 'product:product_single' pro.slug %}">{{ pro.name_en }}</a>
          <div class="new_prod_bg"> <span class="new_icon">
          {% if pro.status == 'new' %}
            <img src="{% static 'images/new_icon.gif' %}" alt="" />
          {% endif %}
          {% if pro.status == 'promo' %}
            <img src="{% static 'images/promo_icon.gif' %}" alt="" />
          {% endif %}
          {% if pro.status == 'special' %}
            <img src="{% static 'images/special_icon.gif' %}" alt="" />
          {% endif %}
          </span> <a href="{% url 'product:product_single' pro.slug %}"><img src="{{ pro.image.url }}" alt="" class="thumb" border="0" /></a> </div>
        </div>
      {% endfor %}


      {% if searchs.has_other_pages %}
        <div class="pagination">
          {% if searchs.has_previous %}
          <a href="?page={{searchs.previous_page_number}}"><<</a>
          {% else %}
          <span class="disabled"><<</span>
          {% endif %}
          {% for i in product.paginator.page_range %} 
            {% if searchs.number == i %}
            <a>{{i}}</a>
            {% else %}
              <a href="?page={{i}}">{{i}}</a>
            {% endif %}
          {% endfor %}
          {% if searchs.has_next %}
            <a href="?page={{searchs.next_page_number}}">>></a>
          {% else %}
          <span class="disabled">>></span>
          {% endif %}
        </div>
      {% endif %}


    </div>
    <div class="clear"></div>
  </div>
{% endif %}

{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}

{%if LANGUAGE_CODE == 'en' %}
  <div class="center_content">
    <div class="left_content">
      <div class="title"><span class="title_icon"><img src="{% static 'images/bullet1.gif' %}" alt="" /></span>{{product.name_en}}</div>
      <div class="feat_prod_box_details">
        <div class="prod_img"><a href=""><img src="{{product.image.url}}" alt="" border="0" /></a> <br />
          <br />
          <a href="{{ product.image.url }}" rel="lightbox"><img src="{% static 'images/zoom.gif' %}" alt="" border="0" /></a> </div>
        <div class="prod_det_box">
          <div class="box_top"></div>
          <div class="box_center">
            <div class="prod_title">Details</div>
            <p class="details">{{product.description_en|truncatechars:200}}<br /></p>
            <div class="price"><strong>PRICE:</strong> <span class="red">{{product.price_end_doller}} $</span></div>
            <div class="price"><strong>COLORS:</strong> <span class="colors"><img src="images/color1.gif" alt="" border="0" /></span> <span class="colors"><img src="images/color2.gif" alt="" border="0" /></span> <span class="colors"><img src="images/color3.gif" alt="" border="0" /></span> </div>
            {% if request.user.is_authenticated and  request.user.is_admin%}
              <li><a href="{% url 'product:edit' product.pk %}">edit</a></li>
            {% endif %}
            {%if product.count > 0 %}
              <a href="{% url 'product:add_to_basket' product.pk %}" class="more"><img src="{% static 'images/order_now.gif' %}" alt="" border="0" /></a>
            {% endif %}
            <div class="clear"></div>
          </div>
          <div class="box_bottom"></div>
        </div>
        <div class="clear"></div>
      </div>
      <div id="demo" class="demolayout">
        <ul id="demo-nav" class="demolayout">
          <li><a class="active" href="#tab1">More details</a></li>
          <li><a class="" href="#tab2">Related Products</a></li>
        </ul>
        <div class="tabs-container">
          <div style="display: block;" class="tab" id="tab1">
            <p class="more_details">{{product.description_en}}</p>
          </div>
          <div style="display: none;" class="tab" id="tab2">
            {% for pro in products %}
              <div class="new_prod_box"> <a href="{% url 'product:product_single' pro.slug %}">{{pro.name_en}}</a>
                <div class="new_prod_bg"> <a href="{% url 'product:product_single' pro.slug %}"><img src="{{pro.image.url}}" alt="" class="thumb" border="0" /></a> </div>
              </div>
            {% endfor %}
            <div class="clear"></div>
          </div>
        </div>
      </div>
      <div class="clear"></div>
    </div>
    
{% endif %}
{%if LANGUAGE_CODE == 'fa' %}
    <div class="center_content">
    <div class="left_content">
      <div class="title"><span class="title_icon"><img src="{% static 'images/bullet1.gif' %}" alt="" /></span>{{product.name}}</div>
      <div class="feat_prod_box_details">
        <div class="prod_img"><a href=""><img src="{{product.image.url}}" alt="" border="0" /></a> <br />
          <br />
          <a href="{{ product.image.url }}" rel="lightbox"><img src="{% static 'images/zoom.gif' %}" alt="" border="0" /></a> </div>
        <div class="prod_det_box">
          <div class="box_top"></div>
          <div class="box_center">
            <div class="prod_title">Details</div>
            <p class="details">{{product.description|truncatechars:200}}<br /></p>
            <div class="price"><strong>PRICE:</strong> <span class="red">{{product.price_end_rial}} $</span></div>
            <div class="price"><strong>COLORS:</strong> <span class="colors"><img src="images/color1.gif" alt="" border="0" /></span> <span class="colors"><img src="images/color2.gif" alt="" border="0" /></span> <span class="colors"><img src="images/color3.gif" alt="" border="0" /></span> </div>
            {% if request.user.is_authenticated and  request.user.is_admin%}
              <li><a href="{% url 'product:edit' product.pk %}">edit</a></li>
            {% endif %}
            <a href="{% url 'product:add_to_basket' product.pk %}" class="more"><img src="{% static 'images/order_now.gif' %}" alt="" border="0" /></a>
            <div class="clear"></div>
          </div>
          <div class="box_bottom"></div>
        </div>
        <div class="clear"></div>
      </div>
      <div id="demo" class="demolayout">
        <ul id="demo-nav" class="demolayout">
          <li><a class="active" href="#tab1">More details</a></li>
          <li><a class="" href="#tab2">Related Products</a></li>
        </ul>
        <div class="tabs-container">
          <div style="display: block;" class="tab" id="tab1">
            <p class="more_details">{{product.description}}</p>
          </div>
          <div style="display: none;" class="tab" id="tab2">
            {% for pro in products %}
              <div class="new_prod_box"> <a href="{% url 'product:product_single' pro.slug %}">{{pro.name}}</a>
                <div class="new_prod_bg"> <a href="{% url 'product:product_single' pro.slug %}"><img src="{{pro.image.url}}" alt="" class="thumb" border="0" /></a> </div>
              </div>
            {% endfor %}
            <div class="clear"></div>
          </div>
        </div>
      </div>
      <div class="clear"></div>
    </div>
    
{% endif %}
{% endblock %}

{% block js %}
<script type="text/javascript">

var tabber1 = new Yetii({
id: 'demo'
});

</script>
{% endblock %}


templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}

{%if LANGUAGE_CODE == 'en' %}

  <div class="center_content">
    <div class="left_content">
      <div class="title"><span class="title_icon"><img src="{% static 'images/bullet1.gif' %}" alt="" /></span>Featured products</div>
      {{LANGUAGE_CODE}}
      {% for pro in product_null%}
        <div class="feat_prod_box">
          <div class="prod_img"><a href="{% url 'product:product_single' pro.slug  %}"><img src="{{ pro.image.url }}" alt="" border="0" /></a></div>
          <div class="prod_det_box">
            <div class="box_top"></div>
            <div class="box_center">
              <div class="prod_title">{{ pro.name_en }}</div>
              <p class="details">{{ pro.description_en|truncatechars:150}}</p>
              <a href="{% url 'product:product_single' pro.slug  %}" class="more">- more details -</a>
              <div class="clear"></div>
            </div>
            <div class="box_bottom"></div>
          </div>
          <div class="clear"></div>
        </div>
      {% endfor %}
     
      <div class="title"><span class="title_icon"><img src="{% static 'images/bullet2.gif' %}" alt="" /></span>New products</div>
      <div class="new_products">
        {% for pro in product_new %}
          <div class="new_prod_box"> <a href="">{{pro.name_en}}</a>
            <div class="new_prod_bg"> <span class="new_icon"><img src="{% static 'images/new_icon.gif' %}" alt="" /></span> <a href="{% url 'product:product_single' pro.slug pro.categoryto.category.name_en %}"><img src="{{ pro.image.url }}" alt="" class="thumb" border="0" /></a> </div>
          </div>
      {% endfor %}
      </div>
      <div class="clear"></div>
    </div>

{% endif %}
{%if LANGUAGE_CODE == 'fa' %}

  <div class="center_content">
    <div class="left_content">
      <div class="title"><span class="title_icon"><img src="{% static 'images/bullet1.gif' %}" alt="" /></span>Featured products</div>
            {{LANGUAGE_CODE}}

      {% for pro in product_null%}
        <div class="feat_prod_box">
          <div class="prod_img"><a href="{% url 'product:product_single' pro.slug  %}"><img src="{{ pro.image.url }}" alt="" border="0" /></a></div>
          <div class="prod_det_box">
            <div class="box_top"></div>
            <div class="box_center">
              <div class="prod_title">{{ pro.name }}</div>
              <p class="details">{{ pro.description |truncatechars:150  }}</p>
              <a href="{% url 'product:product_single' pro.slug  %}" class="more">- more details -</a>
              <div class="clear"></div>
            </div>
            <div class="box_bottom"></div>
          </div>
          <div class="clear"></div>
        </div>
      {% endfor %}
     
      <div class="title"><span class="title_icon"><img src="{% static 'images/bullet2.gif' %}" alt="" /></span>New products</div>
      <div class="new_products">
        {% for pro in product_new %}
          <div class="new_prod_box"> <a href="">{{pro.name}}</a>
            <div class="new_prod_bg"> <span class="new_icon"><img src="{% static 'images/new_icon.gif' %}" alt="" /></span> <a href="{% url 'product:product_single' pro.slug %}"><img src="{{ pro.image.url }}" alt="" class="thumb" border="0" /></a> </div>
          </div>
      {% endfor %}
      </div>
      <div class="clear"></div>
    </div>
{% endif %}

{% endblock %}

templates/myaccount.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block body %}

  <div class="center_content">
    <div class="left_content">
      <div class="title"><span class="title_icon"><img src="{% static 'images/bullet1.gif' %}" alt="" /></span>My account</div>
      <div class="feat_prod_box_details">
        <p class="details">{% trans  "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud." %} </p>
        <div class="contact_form">
          <p class="contact">{% trans "username" %}:<strong>{{request.user.username}}</strong></p>
          <p class="contact">{% trans "email"%}:<strong>{{request.user.email}}</strong></p> 
          {% if request.user.is_authenticated and  request.user.is_admin%}
            <li><a href="{% url 'product:create' %}">create</a></li>
          {% endif %}
          <hr>
          <div class="form_subtitle">{% trans "your account"%}</div>
          <form name="register" action="" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
            <div class="form_row">
              <label class="contact"><strong>{{ field.label }}:</strong></label> <br>
              {{field}}
              <p style="color:tomato">{{ field.errors }}</p>
            </div>
            {% endfor %}
            <div class="form_row">
              <input type="submit" class="register" value="{% trans 'update'%}" />
            </div>
          </form>
        </div>
      </div>
      <div class="clear"></div>
    </div>
{% endblock %}

templates/password_recovery.html
{% autoescape off %}
{% load i18n %}

{% trans 'Hi' %} {{ user.email }},

{% trans 'Please click on the link below to confirm your registration:'%}

http://{{ domain }}{% url 'signin_email' uidb64=uid token=token %}
{% endautoescape %}

templates/register.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block body %}
    <div class="center_content">
      <div class="left_content">
        <div class="title"><span class="title_icon"><img src="{% static 'images/bullet1.gif' %}" alt="" /></span>Register</div>
        <div class="feat_prod_box_details">
          <p class="details"> {% trans 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.'%} </p>
          <div class="contact_form">
            <div class="form_subtitle">{% trans "user identify" %}</div>
            {% if login %}
              <li><a href="{% url 'accounts:recovery' %}">forget password</a></li>
            {% endif %}
            <form name="register"  action="" method='POST' novalidate>
            {% csrf_token %}
              {% for field in form %}  
                <div class="form_row">
                  <label class="contact"><strong>{{field.label}}:</strong></label> <br>
                  {{field}}
                  <p style="color:tomato">{{ field.errors }}</p>
                </div>
              {% endfor %}
              <div class="form_row">
                <input type="submit" class="register" value="{% trans 'submit'%}" />
              </div>
            </form>
          </div>
        </div>
        <div class="clear"></div>
      </div>
{% endblock %}

templates/send.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
<div class="center_content">
    <div class="left_content">
    {% if send %}
        {% for ord in order %}
          <a href="{% url 'product:show_order' ord.pk %}">
            <p>username:<strong><span class="red">{{ord.user.username}}</span></strong>---email:<strong><span class="red">{{ord.user.email}}</span></strong></p>
          </a>
        {% endfor %}
    {% endif %}
    {% if show %}
        {% for pro in products %}
            <div class="new_prod_box"> <a href="{% url 'product:product_single' pro.product.slug %}">{{ pro.product.name }}--تعداد:<strong><span class="red">{{pro.qty}}</span></strong></a>
            <a href="{% url 'product:product_single' pro.product.slug %}"><img src="{{ pro.product.image.url }}" alt="" class="thumb" border="0" /></a> </div>
        {% endfor %}
        <div class="new_products">
            <hr>
            <p>تلفن:{{ address.number }}</p>
            <p>آدرس:{{ address.address }}</p>
            <p> <a href="{% url 'product:is_send' basket.pk %}"> ارسال شده</a></P>
        </div>
    {% endif %}
      <div class="clear"></div>
    </div>
{% endblock %}