accounts/urls.py
from django import urls
from django.urls import path
from .views import signin, signup, profile,signout, recovery

app_name = 'accounts'

urlpatterns = [
    path('signin/', signin, name='signin'),
    path('signup/', signup, name='signup'),
    path('signout/', signout, name='signout'),
    path('profile/', profile, name='profile'),
    path('recovery/', recovery, name='recovery'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import signin_email
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('product.urls')),
    path('signin/email/<uidb64>/<token>/', signin_email, name='signin_email'),
)


if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from .sitemaps import ProductSitemap
from .views import (
                index, is_sending,product_single,delete_product,
                categories,about,all_products,contact_us,
                search, cart,add_to_basket,product_special,
                update_basket,remove_basket,pay,address,
                is_sending,show_order,is_send,create,edit
)

sitemaps = {
    'movie':ProductSitemap,
}

app_name = 'product'

urlpatterns = [
    path('', index, name='index'),
    path('product/single/<str:slug>/',product_single,name='product_single'),
    path('product/special/',product_special,name='product_special'),
    path('about/',about,name='about'),
    path('all/products/',all_products,name="all_products"),
    path('category/<str:name>/',categories,name='category'),
    path('contact/',contact_us,name='contact'),
    path('search/',search,name='search'),
    path('cart',cart ,name='cart'),
    path('add_to_basket/<int:pk>/',add_to_basket ,name='add_to_basket'),
    path('delete_product/', delete_product, name='delete_product'),
    path('update_basket/', update_basket, name='update_basket'),
    path('remove_basket/', remove_basket, name='remove_basket'),
    path('pay/', pay, name='pay'),
    path('address/<int:pk>/', address, name='address'),
    path('is_sending/', is_sending, name='is_sending'),
    path('show_order/<int:pk>/', show_order, name='show_order'),
    path('is_send/<int:pk>/', is_send, name='is_send'),
    path('edit/<int:pk>/', edit, name='edit'),
    path('create/', create, name='create'),
    path('sitemap/', sitemap, {'sitemaps':sitemaps}, name="sitemap"),

]

templates/nav/category.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load i18n_urls %}

{%if LANGUAGE_CODE == 'en' %}
  <!--end of left content-->
    <div class="right_content">

      <div class="languages_box">
      <span class="red">Languages:</span> <a href="{% change_lang 'en' %}" class="selected"><img src="{% static 'images/gb.gif' %}" alt="" border="0" /></a> <a href="{% change_lang 'fa' %}"><img src="{% static 'images/fr.gif' %}" alt="" border="0" /></a></div>
      
      <div class="cart">
        <div class="title"><span class="title_icon"><img src="{% static 'images/cart.gif' %}" alt="" /></span>My cart</div>
        <div class="home_cart_content"> {{user_count}} x items | <span class="red">TOTAL: {{total_doller}}$</span> </div>
        <a href="{% url 'product:cart' %}" class="view_cart">view cart</a> </div>
      <div class="title"><span class="title_icon"><img src="{% static 'images/bullet3.gif' %}" alt="" /></span>About Our Shop</div>
      <div class="about">
        <p> <img src="{% static 'images/about.gif' %}" alt="" class="right" /> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud. </p>
      </div>
      <div class="right_box">
        <div class="title"><span class="title_icon"><img src="{% static 'images/bullet4.gif' %}" alt="" /></span>Promotions</div>
        {% for pro in product_promo %}
            <div class="new_prod_box"> <a href="">{{pro.name_en}}</a>
              <div class="new_prod_bg"> <span class="new_icon"><img src="{% static 'images/promo_icon.gif' %}" alt="" /></span> <a href="{% url 'product:product_single' pro.slug %}"><img src="{{ pro.image.url }}" alt="" class="thumb" border="0" /></a> </div>
            </div>
       {% endfor %}
      </div>
      <div class="right_box">
        <div class="title"><span class="title_icon"><img src="{% static 'images/bullet5.gif' %}" alt="" /></span>Categories</div>
        <ul class="list">
            {% for cat in categories %}         
                <li><a href="{% url 'product:category' cat.name_en %}">{{ cat.name_en }}</a></li>
            {% endfor %}
        </ul>
      </div>
    </div>
{% endif %}


{%if LANGUAGE_CODE == 'fa' %}
      <!--end of left content-->
    <div class="right_content">

      <div class="languages_box">
      <span class="red">Languages:</span> <a href="{% url 'accounts:change_language' 'en' %}?next={{ request.get_full_path }}" ><img src="{% static 'images/gb.gif' %}" alt="" border="0" /></a> <a href="{% url 'accounts:change_language' 'fa' %}" class="selected"><img src="{% static 'images/fr.gif' %}" alt="" border="0" /></a></div>
      
      <div class="cart">
        <div class="title"><span class="title_icon"><img src="{% static 'images/cart.gif' %}" alt="" /></span>My cart</div>
        <div class="home_cart_content"> {{user_count}} x items | <span class="red">TOTAL: {{total_doller}}$</span> </div>
        <a href="{% url 'product:cart' %}" class="view_cart">view cart</a> </div>
      <div class="title"><span class="title_icon"><img src="{% static 'images/bullet3.gif' %}" alt="" /></span>About Our Shop</div>
      <div class="about">
        <p> <img src="{% static 'images/about.gif' %}" alt="" class="right" /> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud. </p>
      </div>
      <div class="right_box">
        <div class="title"><span class="title_icon"><img src="{% static 'images/bullet4.gif' %}" alt="" /></span>Promotions</div>
        {% for pro in product_promo %}
            <div class="new_prod_box"> <a href="">{{pro.name}}</a>
              <div class="new_prod_bg"> <span class="new_icon"><img src="{% static 'images/promo_icon.gif' %}" alt="" /></span> <a href="{% url 'product:product_single' pro.slug %}"><img src="{{ pro.image.url }}" alt="" class="thumb" border="0" /></a> </div>
            </div>
       {% endfor %}
      </div>
      <div class="right_box">
        <div class="title"><span class="title_icon"><img src="{% static 'images/bullet5.gif' %}" alt="" /></span>Categories</div>
        <ul class="list">
            {% for cat in categories %}         
                <li><a href="{% url 'product:category' cat.name_en %}">{{ cat.name }}</a></li>
            {% endfor %}
        </ul>
      </div>
    </div>
{% endif %}

templates/nav/footer.html
{% load static %}
 <!--end of center content-->
  <div class="footer">
    <div class="left_footer"><img src="{% static 'images/footer_logo.gif' %}" alt="" /><br />
      <a href=""><img src="{% static 'images/csscreme.gif' %}" alt="" border="0" /></a></div>
    <div class="right_footer"> <a href="">home</a> <a href="">about us</a> <a href="">services</a> <a href="">privacy policy</a> <a href="">contact us</a> </div>
  </div>
</div>

templates/nav/header.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% url 'product:index' as index%}
{% url 'product:about' as about%}
{% url 'product:all_products' as all_products%}
{% url 'product:product_special' as product_special%}
{% url 'product:contact' as contact%}
{% url 'accounts:signin' as signin%}
{% url 'accounts:signout' as signout%}
{% url 'accounts:profile' as profile%}
{% url 'product:is_sending' as order%}

{%if LANGUAGE_CODE == 'en' %}
<div class="header">
    <div class="logo"><a href=""><img src="{% static 'images/logo.gif' %}" alt="" border="0" /></a></div>

    <div id="menu">
      <ul>
        <li {% if request.path == index %} class="selected" {% endif %} ><a href="{{index}}">home</a></li>
        <li {% if request.path == about %} class="selected" {% endif %} ><a href="{{about}}">about us</a></li>
        <li {% if request.path == all_products %} class="selected" {% endif %} ><a href="{{all_products}}">flowers</a></li>
        <li {% if request.path == product_special %} class="selected" {% endif %}><a href="{{product_special}}">specials gifts</a></li>
        {% if request.user.is_authenticated %}
          <li {% if request.path == profile %} class="selected"{% endif %}><a href="{{profile}}">my accout</a></li>
          <li {% if request.path == signout %} class="selected"{% endif %}><a href="{{signout}}">signout</a></li>
        {% else %}
          <li {% if request.path == signin %} class="selected"{% endif %}><a href="{{signin}}">signup/signin</a></li>
        {% endif %}
          <li {% if request.path == contact %} class="selected"{% endif %}><a href="{{contact}}">contact</a></li>
        {% if request.user.is_authenticated and  request.user.is_admin%}
          <li {% if request.path == order %} class="selected"{% endif %}><a href="{{order}}">order</a></li>
        {% endif %}
      </ul>
    </div>
</div>
{% endif %}
{%if LANGUAGE_CODE == 'fa' %}
<div class="header">
    <div class="logo"><a href=""><img src="{% static 'images/logo.gif' %}" alt="" border="0" /></a></div>
    <div id="menu">
      <ul>
        <li {% if request.path == index %} class="selected" {% endif %} ><a href="{{index}}">خانه</a></li>
        <li {% if request.path == about %} class="selected" {% endif %} ><a href="{{about}}">درباره ما</a></li>
        <li {% if request.path == all_products %} class="selected" {% endif %} ><a href="{{all_products}}">گل ها</a></li>
        <li {% if request.path == product_special %} class="selected" {% endif %}><a href="{{product_special}}">سفارشات مخصوص</a></li>
        {% if request.user.is_authenticated %}
          <li {% if request.path == profile %} class="selected"{% endif %}><a href="{{profile}}">اکانت من</a></li>
          <li {% if request.path == signout %} class="selected"{% endif %}><a href="{{signout}}">خروج</a></li>
        {% else %}
          <li {% if request.path == signin %} class="selected"{% endif %}><a href="{{signin}}">ورود/ثبت نام</a></li>
        {% endif %}<li {% if request.path == contact %} class="selected"{% endif %}><a href="{{contact}}">ارتباط با ما</a></li>
      </ul>
    </div>
</div>
{% endif %}

templates/nav/msg.html
{% if messages %}
    {% for msg in messages %}
        <div class="row">
            <h1 style="background:orange; color:slategrey; text-align: center;" class="col-md-4 alert alert-{{ msg.tags }}">{{ msg }}</h1>
        </div>    
    {% endfor %}
{% endif %}